### ISSUE TITLE
Visual Effect while using Insert Method

### ISSUE THREAD

**Issue by dbo90** [metafizzy/isotope#955]
Hello,

I just updated isotope from V2.0.0 to V2.2.0 on my site, and everything seems to be working just fine, except one thing, let me explain:

I use the "insert" method to add items to the grid (via JS and some Ajax and that kind of stuff), and it is working, it is just that the "visual effect" while inserting is not very smooth anymore, I'll show you an example:

-In V2.0.0 Smooth (with a zoom effect) https://goo.gl/ftMWsr
-In V2.2.0 Not very smooth (all items comes from the top left corner) https://goo.gl/n1gtM1

And I saw that in this commit 5bd5acb7ce933aa8ff00a40e6dbf4e4bc53c36e3 you removed these lines from the insert method:
<pre>
// hide all newitems
this._noTransition( function() {
  this.hide( filteredInsertItems );
});
</pre>

If I add those lines back to the insert method, the smooth effect comes back to normal :D, so this solves the issue, but I just wanted to know if there's any reason why you removed those lines? in other words, do you think I'll have a side effect if I add those lines back?

thank you for your time, your script is really awesome by the way :D

**Comment by desandro** [comment]
Thanks for reporting this issue. This is likely related to #948. This should be fixed in the next release.

**Comment by desandro** [comment]
Fixed in Isotope v2.2.2. Give it a shot :whale:

**Comment by dbo90** [comment]
thank's for answering, I gave it a shot and the issue persists! (I even clear the cache and everything)

I don't see any change in the insert method here: https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.2.2/isotope.pkgd.js (maybe the change was somewhere else)

if I add again this peace of JS in the insert method it works

<pre>
// hide all newitems
this._noTransition( function() {
  this.hide( filteredInsertItems );
});
</pre>

**Comment by desandro** [comment]
Thanks for trying? Could you try putting together a **reduced test case** so I can see this bug in effect? You can fork the insert CodePen: http://codepen.io/desandro/pen/byqcz

**Comment by dbo90** [comment]
I found the problem, if I apply the ".hide()" jQuery method to the elements before the insert it shows the bug!

for example in the CodePen example you can reproduce the issue if instead of having this:
<pre>
// insert new elements
$grid.isotope( 'insert', $items );
</pre>
 you add ".hide()" like this:
<pre>
// insert new elements
$grid.isotope( 'insert', $items.hide() );
</pre>

anyhow, I removed the ".hide()" from my code and it works like a charm! thank you for your prompt responses!

**Comment by desandro** [comment]
Thanks for following up!
